version: '3'

services:

    brocolib:
        image: brocolidata/brocolib
        container_name: brocolib
        volumes:
            - ./src:/src
            - ./credentials:/credentials
        environment:
          - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
        stdin_open: true
        tty: true