version: '3'

services:

    brocolib:
        image: brocolidata/brocolib
        container_name: brocolib
        volumes:
            - ./src:/src
            - ./credentials:/credentials
        environment:
          - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
          - DATALAKE_BUCKET=$DATALAKE_BUCKET
          - PROJECT_ID=$PROJECT_ID
          - DEFAULT_GCS_PARTITIONNING_KEYS=$DEFAULT_GCS_PARTITIONNING_KEYS
        working_dir: /src
        stdin_open: true
        tty: true