version: '3'

services:

    brocolib:
        image: brocolidata/brocolib
        container_name: brocolib
        volumes:
            - ./brocolib:/brocolib
        stdin_open: true
        tty: true