name: Brocolib CD

on:
  pull_request: 
    types:
      - closed 

jobs:
  changes:
    name: Check files for changes
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      extract_load: ${{ steps.filter.outputs.extract_load }}
      transform: ${{ steps.filter.outputs.transform }}
      utils: ${{ steps.filter.outputs.utils }}
      factory_utils: ${{ steps.filter.outputs.factory_utils }}
      changed_projects: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            extract_load:
              - 'brocolib/extract_load/**'
            transform:
              - 'brocolib/transform/**'
            utils:
              - 'brocolib/utils/**'
            factory_utils:
              - 'brocolib/factory_utils/**'

  build_brocolib:
    name: 'Release ${{ matrix.changed_project }}'
    needs: changes
    strategy:
      matrix:
        changed_project: ${{ fromJSON(needs.changes.outputs.changed_projects) }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: 'Install dependencies'
        working-directory: ${{ github.workspace }}/brocolib/${{ matrix.changed_project }}
        run: |
          pip install wheel 
          echo "PYTHONPATH=${{ github.workspace }}/brocolib/${{ matrix.changed_project }}" >> $GITHUB_ENV
          python setup.py install --user
      - name: Build ${{ matrix.changed_project }} distribution
        id: build_distribution
        working-directory: ${{ github.workspace }}/brocolib/${{ matrix.changed_project }}
        run: |
          python setup.py sdist bdist_wheel
          echo "BROCOLIB_PACKAGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
      - name: 'Create ${{ matrix.changed_project }} release'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: '${{ matrix.changed_project }} v${{ env.BROCOLIB_PACKAGE_VERSION }}'
          tag_name: '${{ matrix.changed_project }}_v_${{ env.BROCOLIB_PACKAGE_VERSION }}'
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/brocolib/${{ matrix.changed_project }}/dist/**

      - name: 'Publish release'
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      