name: 'Deploy documentation'

on:
  push:
    branches:
      - main
jobs:
  deploy_docs:
    name: Check files for changes
    if: github.event
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: 'Add brocolib modules to path'
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE/brocolib/extract_load" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE/brocolib/transform" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE/brocolib/utils" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE/brocolib/factory_utils" >> $GITHUB_ENV
      - name: 'Install Python dependencies'
        run: pip install -r ${{ github.workspace }}/docker_build/requirements.txt
      - name: 'Build docs'
        working-directory: ${{ github.workspace }}/brocolib
        run: portray as_html -o ${{env.GITHUB_WORKSPACE}}/docs
      - name: 'Upload GitHub Pages artifact'
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: '${{env.GITHUB_WORKSPACE}}/docs'
      - name: 'Deploy GitHub Pages site'
        uses: actions/deploy-pages@v1.2.3
