## Useful links : 
# - https://github.community/t/run-job-only-if-folder-changed/118292/2
name: Pytest CI

on:
  pull_request:

jobs:
  changes:
    name: Check files for changes
    runs-on: ubuntu-latest
    outputs:
      extract_load: ${{ steps.filter.outputs.extract_load }}
      transform: ${{ steps.filter.outputs.transform }}
      utils: ${{ steps.filter.outputs.utils }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            extract_load:
              - 'src/extract_load/**'
            transform:
              - 'src/transform/**'
            utils:
              - 'src/utils/**'

  brocolib_extract_load_tests:
    name: Job for 'brocolib_extract_load' package
    needs: changes
    if: ${{ needs.changes.outputs.extract_load == 'true' }}
    runs-on: ubuntu-latest
    env:
      tests_directory: src/tests
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        working-directory: src/extract_load
        run: python setup.py install

      - name: Run tests for 'brocolib_extract_load' folder
        working-directory: ${{ github.workspace }}/src/tests/extract_load
        run: python -m pytest --junit-xml pytest_extract_load.xml

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: pytest_extract_load.xml

  brocolib_transform_tests:
    name: Job for 'brocolib_transform' package
    needs: changes
    if: ${{ needs.changes.outputs.transform == 'true' }}
    runs-on: ubuntu-latest
    env:
      tests_directory: ${{ github.workspace }}/src/tests
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        working-directory: ${{ github.workspace }}/src/transform
        run: python setup.py install

      - name: Run tests for 'brocolib_transform' folder
        working-directory: ${{ github.workspace }}/src/tests/transform
        run: python -m pytest --junit-xml pytest_transform.xml

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: pytest_transform.xml

  brocolib_utils_tests:
    name: Job for 'brocolib_utils' package
    needs: changes
    if: ${{ needs.changes.outputs.utils == 'true' }}
    runs-on: ubuntu-latest
    env:
      tests_directory: ${{ github.workspace }}/src/tests
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - name: 'Install dependencies'
        working-directory: ${{ github.workspace }}/src/utils
        run: python setup.py install

      - name: Run tests for 'brocolib_utils' folder
        working-directory: ${{ github.workspace }}/src/tests/utils
        run: python -m pytest --junit-xml pytest_utils.xml

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: pytest_utils.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: [brocolib_extract_load_tests, brocolib_transform_tests, brocolib_utils_tests]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
