name: 'Pytest CI new'

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  changes:
    name: 'Check files for changes'
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.filter.outputs.changes }}
    steps:
      - name: 'Filter changes'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            extract_load:
              - 'brocolib/extract_load/**'
              - 'brocolib/tests/extract_load/**'
            transform:
              - 'brocolib/transform/**'
              - 'brocolib/tests/transform/**'
            utils:
              - 'brocolib/utils/**'
              - 'brocolib/tests/utils/**'
            factory_utils:
              - 'brocolib/factory_utils/**'
              - 'brocolib/tests/factory_utils/**'
            
  brocolib_run_tests:
    name: 'Test ${{ matrix.changed_project }}'
    needs: changes
    continue-on-error: true
    strategy:
      matrix:
        changed_project: ${{ fromJSON(needs.changes.outputs.changed_projects) }}
    # if: ${{ needs.changes.outputs.extract_load == 'true' }} || ${{ needs.changes.outputs.transform == 'true' }} || ${{ needs.changes.outputs.utils == 'true' }} || ${{ needs.changes.outputs.factory_utils == 'true' }}
    runs-on: ubuntu-latest
    env:
      DATALAKE_BUCKET: ${{ secrets.DATALAKE_BUCKET }}
      DBT_DOCS_BUCKET: ${{ secrets.DBT_DOCS_BUCKET }}
      BACK_PROJECT_ID: ${{ secrets.BACK_PROJECT_ID }}
      FRONT_PROJECT_ID: ${{ secrets.FRONT_PROJECT_ID }}
      DDM_SHEETS_ID: ${{ secrets.TEST_DDM_SHEETS_ID }}
      DBT_DOCS_READ_GROUP: ${{ secrets.DBT_DOCS_READ_GROUP }}
      DEFAULT_GCS_PARTITIONNING_KEYS: '["year","month"]'
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: 'Authenticate gcloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_SECRETS_ACCESS_SA }}'
      - name: 'Install apt dependencies'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc
          version: 1.0
      - name: 'Install test dependencies'
        run: |
          pip install pytest poetry
          pip list
      - name: 'Install ${{ matrix.changed_project }} dependencies'
        id: install_dependencies
        working-directory: ${{ github.workspace }}/brocolib/${{ matrix.changed_project }}
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/brocolib/${{ matrix.changed_project }}" >> $GITHUB_ENV
          poetry install --no-root
          poetry show
      - name: 'Run ${{ matrix.changed_project }} tests'
        id: run_tests
        if: steps.install_dependencies.outcome == 'success'
        working-directory: ${{ github.workspace }}/brocolib/${{ matrix.changed_project }}/tests
        run: poetry run pytest --junit-xml pytest_brocolib_${{ matrix.changed_project }}.xml
      - name: 'Upload tests ${{ matrix.changed_project }} test results'
        if: steps.run_tests.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.changed_project }} unit test results
          path: ${{ github.workspace }}/brocolib/tests/pytest_brocolib_${{ matrix.changed_project }}.xml

  publish-test-results:
    name: 'Publish tests results'
    needs: [brocolib_run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifacts'
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: 'Publish tests results'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
