## Useful links : 
# - https://github.community/t/run-job-only-if-folder-changed/118292/2
name: Pytest CI

on:
  pull_request:

jobs:
  changes:
    name: Check files for changes
    runs-on: ubuntu-latest
    outputs:
      extract_load: ${{ steps.filter.outputs.extract_load }}
      transform: ${{ steps.filter.outputs.transform }}
      utils: ${{ steps.filter.outputs.utils }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            extract_load:
              - 'src/extract_load/**'
              - 'src/tests/extract_load/**'
            transform:
              - 'src/transform/**'
              - 'src/tests/transform/**'
            utils:
              - 'src/utils/**'
              - 'src/tests/utils/**'

  brocolib_run_tests:
    name: Run tests for brocolib packages
    needs: changes
    if: ${{ needs.changes.outputs.extract_load == 'true' }} || ${{ needs.changes.outputs.transform == 'true' }} || ${{ needs.changes.outputs.utils == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: 'Install pytest'
        run: pip install pytest
      - name: 'Install dependencies for extract_load'
        if: ${{ needs.changes.outputs.extract_load == 'true' }}
        working-directory: ${{ github.workspace }}/src/extract_load
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src/extract_load" >> $GITHUB_ENV
          echo "EXTRACT_LOAD_PATH=extract_load" >> $GITHUB_ENV
          python setup.py install --user
      - name: 'Install dependencies for transform'
        if: ${{ needs.changes.outputs.transform == 'true' }}
        working-directory: ${{ github.workspace }}/src/transform
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src/transform" >> $GITHUB_ENV
          echo "TRANSFORM_PATH=transform" >> $GITHUB_ENV
          python setup.py install --user
      - name: 'Install dependencies for utils'
        if: ${{ needs.changes.outputs.utils == 'true' }}
        working-directory: ${{ github.workspace }}/src/utils
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src/utils" >> $GITHUB_ENV
          echo "UTILS_PATH=utils" >> $GITHUB_ENV
          python setup.py install --user
      - name: Run tests
        working-directory: ${{ github.workspace }}/src/tests
        run: python -m pytest $EXTRACT_LOAD_PATH $TRANSFORM_PATH $UTILS_PATH --junit-xml pytest_brocolib.xml
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/src/tests/pytest_brocolib.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: brocolib_run_tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
